### ISSUE TITLE
Alternative to WebRTC

### ISSUE THREAD

**Issue by borkform2555** [hyalusapp/hyalus#57]
WebRTC leaks IP.

**Comment by gidoBOSSftw5731** [comment]
There's no intention of fixing as of now due to the 1. lack of good alternatives to webrtc 2. due to everything being e2ee, our current key-management system would not actually reduce bandwidth on the senders side and 3. @asineth0 does not have the bandwidth capacity for a TURN server and seems uninterested in finding other solutions (due to the previous 2 reasons). 

If you care that much about your IP leaking, use a proxy

**Comment by asineth0** [comment]
No.

* Hosting servers and routing all your call traffic through it gets very expensive (bandwidth).
* WebRTC is a versatile and open standard, allowing us to support many platforms.
* Calls being peer-to-peer provide some benefits, especially latency.
* if you're concerned about leaking your IP, use Tor. (We may even provide this built-in to the desktop app!)

**Comment by asineth0** [comment]
If you have any ideas or suggestions, let me know. But as of now, I don't really see any other options other than our current solution.
