### ISSUE TITLE
When you haven't sent a message it is unix start time

### ISSUE THREAD

**Issue by Xaglinath** [hyalusapp/hyalus#63]

**Comment by Xaglinath** [comment]
![image](https://user-images.githubusercontent.com/59151002/130331483-f92bf296-af67-4859-a872-c5f6a2486488.png)

**Comment by asineth0** [comment]
Won't be an issue going forward, since channels must always have a message (either friendAccept or groupCreate). If it bothers you that much, our official statement/solution would be to send a message in the channel to resolve the issue. Also refrain from deleting said message if you don't want the issue to return.
